BUILD: Updated prebuild.ps1 to build 32 bit if -32bit is set. Updated shared-build-and-test-stage.yml to build and test 32bit.

diff --git a/ci/shared-build-and-test-stage.yml b/ci/shared-build-and-test-stage.yml
--- a/ci/shared-build-and-test-stage.yml
+++ b/ci/shared-build-and-test-stage.yml
@@ -21,10 +21,18 @@ stages:
 
       strategy:
         matrix:
-          Ubuntu 18:
+          Ubuntu 18 x86:
             imageName: 'ubuntu-18.04'
-          Ubuntu 20:
+            platform: 'x86'
+          Ubuntu 18 x64:
+            imageName: 'ubuntu-18.04'
+            platform: 'x64'
+          Ubuntu 20 x86:
             imageName: 'ubuntu-20.04'
+            platform: 'x86'
+          Ubuntu 20 x64:
+            imageName: 'ubuntu-20.04'
+            platform: 'x64'
 
       pool:
         vmImage: $(imageName)
@@ -42,24 +50,60 @@ stages:
             g++-multilib        
         displayName: 'Install Required Packages'
 
+      # Install go
+      - task: GoTool@0
+        displayName: 'Use go ${{ parameters.goVersion }} 64bit'
+        inputs:
+          version: '${{ parameters.goVersion }}'
+        condition: and(succeeded(), eq(variables['platform'], 'x64'))
+
+      # Install go for 32bit
+      - bash: |
+          # Download go package
+          wget https://golang.org/dl/go${{ parameters.goVersion }}.linux-386.tar.gz
+          if [ $? -ne 0 ]; then
+            echo "Failed to download 32bit go."
+            exit 1
+          fi
+
+          # Extract to one directory above
+          tar -xvf ./go${{ parameters.goVersion }}.linux-386.tar.gz -C ../
+          if [ $? -ne 0 ]; then
+            echo "Failed to extract 32bit go package."
+            exit 1
+          fi
+        displayName: 'Install golang 32bit ${{ parameters.goVersion }}'
+        condition: and(succeeded(), eq(variables['platform'], 'x86'))
+
       # Run prebuild
       - powershell: |
-          ./dd/scripts/prebuild.ps1
+          if [ $(platform) -eq 'x86']; then
+            ./dd/scripts/prebuild.ps1 -32bit
+          else
+            ./dd/scrtips/prebuild.ps1
+          fi
         displayName: 'Build device detection core binaries'
         workingDirectory: '$(Build.SourcesDirectory)'
 
-      # Install go
-      - task: GoTool@0
-        displayName: 'Use go ${{ parameters.goVersion }}'
-        inputs:
-          version: '${{ parameters.goVersion }}'
-
       # Run test
       - task: Go@0
-        displayName: 'Run tests'
+        displayName: 'Run 64bit tests'
         inputs:
           command: test
           arguments: './...'
+        condition: and(succeeded(), eq(variables['platform'], 'x64'))
+      
+      # Run 32bit test. Go packages was installed in previous task
+      - bash: |
+          export PATH=$PWD/../go/bin:$PATH
+          export GOROOT=$PWD/../go
+          # Print out go version
+          go version
+
+          # Run test
+          go test './...'
+        displayName: 'Run 32bit tests'
+        condition: and(succeeded(), eq(variables['platform'], 'x86'))
 
 - stage: MacOS
   dependsOn: []
